package com.aplos.controller;

import com.aplos.common.dto.ClientRatingDto;
import com.aplos.common.dto.ResponseDto;
import com.aplos.service.ClientCityService;
import com.aplos.service.ClientRatingService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

/**
 * Created by Aux072 on 15/05/2018.
 */
@RestController
@RequestMapping("/clientRating")
public class ClientRatingController {

    private final static Logger LOGGER = LoggerFactory.getLogger(ClientRatingController.class);

    @Autowired
    ClientRatingService clientRatingService;

    @RequestMapping(value = "", method = RequestMethod.POST)
    public ResponseDto addClientRating(@RequestBody ClientRatingDto clientRatingDto) {
        LOGGER.info(
                "ClientRatingController.addClientRating() invoked.");
        return clientRatingService.addClientRating(clientRatingDto);
    }

    @RequestMapping(value = "/getAllRatingByClientId", method = RequestMethod.GET)
    public ResponseDto getAllRatingByClientId(@RequestParam("client_id") Long clientId) {
        LOGGER.info(
                "ClientRatingController.getAllRatingByClientId(Long {} ) invoked.",clientId);
        return clientRatingService.getAllRatingByClientId(clientId);
    }

    @RequestMapping(value = "/addAutoGeneratedValues", method = RequestMethod.POST)
    public ResponseDto addAutoGeneratedValues(@RequestParam("client_id") Long clientId,
                                       @RequestParam("user_id") Long userId,
                                       @RequestParam("baseOf") String baseOf) {
        LOGGER.info(
                "ClientRatingController.addAutoGeneratedValues() invoked.");
        return clientRatingService.addAutoGeneratedValues(clientId, userId, baseOf);
    }
}
